### ISSUE TITLE
Reorganizar y modularizar la documentación

### ISSUE THREAD

**Issue by AntonyFagundez** [alkemyTech/OT129-CLIENT#156]
Como hicimos con los test lo ideal sería que  los componentes tengan su Readme especifico y linkearlo con el principal.
```
- component
  --index.js
  --README.md
-README.md
```

Y agregar una seccion en el README principal con la seccion de `componentes reutilizables`

**Comment by emquiroga** [comment]
@FabricioCapiglioni es muy bueno documentando, yo lo propongo para hacer este issue 🥇

**Comment by FabricioCapiglioni** [comment]
Yo lo hago 💪
