### ISSUE TITLE
Pagina Nosotros: Responsive

### ISSUE THREAD

**Issue by AntonyFagundez** [alkemyTech/OT129-CLIENT#168]
La página y layout rompen apartir de ~440px.

![image](https://user-images.githubusercontent.com/47680399/155902396-3ba13b98-e6c3-4cfe-8cbd-c5634f745594.png)
![image](https://user-images.githubusercontent.com/47680399/155902406-fa9f57ca-1f3a-4a9c-869d-d5994a93eec4.png)

**Comment by anagalli** [comment]
Hola! Ahí lo comenté en el otro issue, pero lo pongo acá de nuevo por las dudas. Ya estoy trabajando en ésto.

**Comment by anagalli** [comment]
Responsive para Nosotros y los detalles de las cards de Actividades y Novedades.
