### ISSUE TITLE
Novedades detalles

### ISSUE THREAD

**Issue by AntonyFagundez** [alkemyTech/OT129-CLIENT#169]
Al seleccionar este detalle de novedades rompe.
![image](https://user-images.githubusercontent.com/47680399/155902485-d33d707d-a972-4f0c-8b4d-3fefba829785.png)

**Comment by anagalli** [comment]
Hola Antony! Justo arranqué para acomodar los detalles de Novedades y Actividades y el responsive de Nosotros. Estoy trabajando en eso.
