### ISSUE TITLE
Titulo y Metadata acorde al proyecto

### ISSUE THREAD

**Issue by AntonyFagundez** [alkemyTech/OT129-CLIENT#172]
![image](https://user-images.githubusercontent.com/47680399/155902740-c5ddc849-8bfc-4dc1-bf7e-3237b492f740.png)

Debería ser Somos Más, e incluir el logo de la organizacion

**Comment by AstridMata** [comment]
![image](https://user-images.githubusercontent.com/86080960/156067262-8ec645b3-817d-44b0-a0da-e65cbc26c61a.png)
![image](https://user-images.githubusercontent.com/86080960/156067425-ba91e553-6994-4cf5-a99f-5491de160429.png)
